version: '3'
services:
    web:
        build:
            context: ./
            dockerfile: docker/web/prod/Dockerfile
        environment:
            PORT: 33287
        ports:
            - "33287:33287"