services:
    frontend:
        image: ghcr.io/joebobmiles/hullabaloo-frontend
        build:
            context: ./
            dockerfile: ./docker/frontend/prod.Dockerfile

        restart: unless-stopped

        ports:
            - "${DOCKER_FRONTEND_HOST_PORT}:${DOCKER_FRONTEND_CLIENT_PORT}"

        environment:
            HOSTNAME: "0.0.0.0"
            PORT: "${DOCKER_FRONTEND_CLIENT_PORT}"
            NEXT_PUBLIC_API_BASE_URL: "${DOCKER_BACKEND_BASE_URL}"

    backend:
        image: ghcr.io/joebobmiles/hullabaloo-backend
        build:
            context: ./packages/backend
            dockerfile: ./docker/prod.Dockerfile
            args:
                PORT: $DOCKER_BACKEND_CLIENT_PORT

        restart: unless-stopped

        ports:
            - "${DOCKER_BACKEND_HOST_PORT}:${DOCKER_BACKEND_CLIENT_PORT}"