services:
    frontend:
        image: hullabaloo/frontend
        build:
            context: ./packages/frontend
            dockerfile: ./docker/prod.Dockerfile

        restart: unless-stopped

        env_file: .env
        ports:
            - "${DOCKER_FRONTEND_HOST_PORT}:${DOCKER_FRONTEND_CLIENT_PORT}"

    backend:
        image: hullabaloo/backend
        build:
            context: ./packages/backend
            dockerfile: ./docker/prod.Dockerfile
            args:
                PORT: $DOCKER_BACKEND_CLIENT_PORT

        restart: unless-stopped

        env_file: .env
        ports:
            - "${DOCKER_BACKEND_HOST_PORT}:${DOCKER_BACKEND_CLIENT_PORT}"