version: '3'
services:
    backend:
        build:
            context: ./
            dockerfile: docker/web/prod/Dockerfile
        image: hullabaloo/backend
        restart: always
        environment:
            PORT: 33287
        ports:
            - "33287:33287"