services:
    backend:
        image: hullabaloo/backend
        build:
            context: ./
            dockerfile: docker/backend/prod/Dockerfile
        restart: unless-stopped
        env_file: ".env"
        ports:
            - "127.0.0.1:${DOCKER_BACKEND_HOST_PORT:-33287}:${PORT:-33287}"