name: Build & Push Container

on:
  push:
    branches: [ master ]

jobs:
  build-container:
    name: "Build and push container"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: jacobtomlinson/gha-find-replace@v2
        with:
          id: find-replace
          find: "http://localhost(:[0-9]+)?"
          replace: "https://feed.jrm.dev/api"
          include: "**index.html"

      - run: |
        if [[ ${{ steps.find-replace.outputs.modifiedFiles }} != 0 ]]; then exit 0; else exit 1; fi

      - name: Copy environment file
        run: cp .env.example .env

      - name: Copy override file
        run: cp docker-compose.override.yml.example docker-compose.override.yml

      - name: Build containers
        run: docker-compose build

      - name: Login into Docker
        run: echo ${DOCKER_TOKEN} | docker login --username ${DOCKER_USER} --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: Push containers
        run: docker-compose push