name: Build & Push Container

on:
  push:
    branches: [ master ]

jobs:
  build-container:
    name: "Build and push container"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Copy environment file
        run: cp .env.example .env

      - name: Copy override file
        run: cp docker-compose.override.yml.example docker-compose.override.yml

      - name: Build container
        run: docker-compose build backend

      - name: Login into Docker
        run: echo ${DOCKER_TOKEN} | docker login --username ${DOCKER_USER} --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

      - name: Push container
        run: docker-compose push backend